import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  container:{
    textAlign: 'center',
    margin: '0 auto',
    webkitPerspective: 1200,
    perspective: 1200,
    mozTransform: 'perspective(1200px)',
    webkitTransformStyle: 'preserve-3d',
    mozTransformStyle: 'preserve-3d',
    transformStyle: 'preserve-3d',
  },
  flipper: {
    position: 'relative',
    height: '628px',
    webkitTransformStyle: 'preserve-3d',
    mozTransformStyle: 'preserve-3d',
    transformStyle: 'preserve-3d',
    webkitTransition: '.3s linear',
    mozTransition: '.3s linear',
    oTransition: '.3s linear',
    transition: '.3s linear',
    boxShadow: '0px 3px 5px -1px rgb(0 0 0 / 20%), 0px 5px 8px 0px rgb(0 0 0 / 14%), 0px 1px 14px 0px rgb(0 0 0 / 12%)',
    background: '#fff',
  },
  flip: {
    webkitTransform: 'rotateY(180deg)',
    mozTransform: 'rotateY(180deg)',
    msTransform: 'rotateY(180deg)',
    transform: 'rotateY(180deg)',
  },
  card: {
    position: 'absolute',
    top: 0,
    left: 0,
    padding: 16,
    boxSizing: 'border-box',
    width: '100%',
    height: '100%',
    webkitBackfaceSisibility: 'hidden',
    mozBackfaceSisibility: 'hidden',
    backfaceVisibility: 'hidden',
  },
  front: {
    zIndex: 2,
    lineHeight: '600px',
    webkitTransform: 'rotateY(0deg)',
    mozTransform: 'rotateY(0deg)',
    msTransform: 'rotateY(0deg)',
    transform: 'rotateY(0deg)',
  },
  back: {
    webkitTransform: 'rotateY(-180deg)',
    mozTransform: 'rotateY(-180deg)',
    msTransform: 'rotateY(-180deg)',
    transform: 'rotateY(-180deg)',
  },
  addFab: {
    color: 'white',
    background: 'linear-gradient(60deg, #66bb6a, #43a047)',
    width: 80,
    height: 80,
    '& svg': {
      width: '2.5em',
      height: '2.5em',
    },
  },
}));